FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

# Copy config
COPY nginx/default.conf /etc/nginx/conf.d/

# Copy React build
COPY frontend/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
